services:
  library_cleanser:
    build: .
    container_name: library_cleanser
    depends_on:
      - ai_model
      - sqlite
    environment:
      - AI_API_KEY=${AI_API_KEY}
      - DB_PATH=/data/library.db
    volumes:
      - ./raw_data:/app/raw_data:ro
      - ./output_cleansed_data:/app/output_cleansed_data
      - ./data:/data
    command:
      [
        "python",
        "cleanse_library_data.py",
        "--customers-input",
        "/app/raw_data/03_Library SystemCustomers.csv",
        "--customers-output",
        "/app/output_cleansed_data/cleansed_system_customers.csv",
        "--books-input",
        "/app/raw_data/03_Library Systembook.csv",
        "--books-output",
        "/app/output_cleansed_data/cleansed_system_book.csv",
        "--db-path",
        "/data/library.db",
        "--books-metrics-output",
        "/app/output_cleansed_data/metrics.csv"
      ]

  sqlite:
    image: alpine:latest
    container_name: sqlite_client
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    entrypoint: sh

  ai_model:
    image: ollama/ollama:latest
    container_name: ai_model
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h

  streamlit:
    build: ./streamlit/
    volumes:
      - ./data:/data
    ports:
      - "8502:8502"

  sqlite_web:
      depends_on:
        - sqlite
      image: coleifer/sqlite-web:latest
      container_name: sqlite_web
      ports:
        - "8080:8080"
      volumes:
        - ./data:/data:ro
      environment:
        - SQLITE_DATABASE=library.db

